version: '3.8'

networks:
  cooperadora_network:
    driver: bridge

services:
  postgres:
    image: postgres:15-alpine
    container_name: cooperadora_docker_db
    environment:
      POSTGRES_DB: cooperadora_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"               # 5433 en host → 5432 en contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Persistencia de datos
    networks:
      - cooperadora_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_cooperadora
    environment:
      PGADMIN_DEFAULT_EMAIL: cooperadora@cooperadora.com
      PGADMIN_DEFAULT_PASSWORD: cooperadora
    ports:
      - "5051:80"                  # Accedes a pgAdmin en http://localhost:5051
    depends_on:
      - postgres
    networks:
      - cooperadora_network

  api:
    image: ghcr.io/cooperadora-escuela/cooperadora-back:latest
    container_name: cooperadora_api
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-oid1ss30=a%amea1noa%7)7ch=^f#e(1j0g#$_e@x78kc#@jmg
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=cooperadora_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DEBUG=1
    volumes:
      - media_data:/app/media
    depends_on:
      - postgres
    networks:
      - cooperadora_network

  front:
    image: ghcr.io/cooperadora-escuela/cooperadora-front:latest
    container_name: cooperadora_front
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - cooperadora_network

volumes:
  postgres_data:
  media_data: