# Generated by Django 5.1.6 on 2026-03-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración anual',
                'verbose_name_plural': 'Configuraciones anuales',
                'ordering': ['-anio'],
            },
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='CuotaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True, help_text='Permite deshabilitar una cuota sin eliminarla')),
            ],
            options={
                'verbose_name': 'Cuota mensual',
                'verbose_name_plural': 'Cuotas mensuales',
                'ordering': ['anio', 'mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°'), (7, '7°')])),
                ('letra', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='Opcional, ej: A, B, C', max_length=1)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['numero', 'letra'],
                'unique_together': {('numero', 'letra')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True, help_text='Indica si es la inscripción actual del alumno')),
                ('modalidad', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='core.grado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-anio', 'usuario__apellido', 'usuario__nombre'],
                'unique_together': {('usuario', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensual', 'Cuota mensual'), ('anual', 'Pago anual'), ('donacion', 'Donación')], max_length=10)),
                ('mes', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text="Obligatorio si tipo es 'mensual'", null=True)),
                ('anio', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.inscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'mensual')), fields=('inscripcion', 'tipo', 'mes', 'anio'), name='unique_pago_mensual'), models.UniqueConstraint(condition=models.Q(('tipo', 'anual')), fields=('inscripcion',), name='unique_pago_anual')],
            },
        ),
    ]
