# Generated by Django 5.1.6 on 2026-03-31 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionanual_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='padre',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'PAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
