# Generated by Django 5.1.6 on 2026-05-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='encabezado',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/portadas/'),
        ),
        migrations.CreateModel(
            name='PublicacionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.publicacion')),
            ],
            options={
                'verbose_name': 'Imagen de publicación',
                'verbose_name_plural': 'Imágenes de publicaciones',
                'ordering': ['orden'],
            },
        ),
    ]
