# Generated by Django 5.1.6 on 2026-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicacion_encabezado_publicacion_imagen_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='token_mint_tx',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='token_minteado',
            field=models.BooleanField(default=False),
        ),
    ]
