# Generated by Django 5.1.6 on 2026-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pago_token_minteado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='wallet_private_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
