# Generated by Django 5.1.6 on 2026-05-26 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_usuario_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_escuela', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('dao_address', models.CharField(blank=True, max_length=42)),
                ('subscription_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('TRIAL', 'Período de prueba'), ('ACTIVE', 'Activa'), ('EXPIRED', 'Vencida'), ('SUSPENDED', 'Suspendida')], default='PENDING', max_length=10)),
                ('trial_until', models.DateField(blank=True, null=True)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cooperadora',
                'verbose_name_plural': 'Cooperadoras',
                'db_table': 'cooperadoras',
            },
        ),
        migrations.AlterField(
            model_name='configuracionanual',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cuotamensual',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configuracionanual',
            name='cooperadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_anuales', to='core.cooperadora'),
        ),
        migrations.AddField(
            model_name='cuotamensual',
            name='cooperadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_mensuales', to='core.cooperadora'),
        ),
        migrations.AddField(
            model_name='grado',
            name='cooperadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='core.cooperadora'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cooperadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.cooperadora'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cooperadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.cooperadora'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='cooperadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='core.cooperadora'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cooperadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.cooperadora'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionanual',
            unique_together={('cooperadora', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='cuotamensual',
            unique_together={('cooperadora', 'anio', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='grado',
            unique_together={('cooperadora', 'numero', 'letra')},
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('cooperadora', 'dni'), name='unique_usuario_dni_por_cooperadora'),
        ),
    ]
