# Generated by Django 5.1.6 on 2026-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_cooperadora_27'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperadora',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cooperadora',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
