# Generated by Django 5.1.6 on 2026-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_key_revealed_to_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperadora',
            name='afip_punto_venta',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de punto de venta habilitado en AFIP', null=True),
        ),
        migrations.AddField(
            model_name='cooperadora',
            name='cuit',
            field=models.CharField(blank=True, help_text='Formato: XX-XXXXXXXX-X', max_length=13),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura_cae',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura_emitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura_numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura_vencimiento_cae',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cuil',
            field=models.CharField(blank=True, help_text='Formato: XX-XXXXXXXX-X', max_length=13),
        ),
    ]
